name: Deploy Develop Theme

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Develop Theme
    runs-on: ubuntu-latest
    steps:
      # basically git clone
      - uses: actions/checkout@v2
      # - run: npm install
      # - run: npm run build
      # deploy shopify theme
      - uses: pgrimaud/action-shopify@2.2.2
        env:
          SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_STORE_PASSWORD }}
          SHOPIFY_STORE_URL: ${{ secrets.SHOPIFY_STORE_URL }}
          SHOPIFY_THEME_ID: ${{ secrets.SHOPIFY_DEVELOP_THEME_ID }}
        with:
          args: --ignored-file=config/settings_data.json --ignored-file=locales/*
